name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 */18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: itxfida/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: ${{ github.repository_count }}
      - name: Commit & Push
        run: |
          git config user.name itxfida
          git config user.email se120202011@kust.edu.pk
          git add -A .
          git commit -m "Personal 3d Contributions images updated"
          git push
